name: Save BTRFS
description: Composite action that sets up the BTRFS volume for the runner
inputs:
  key:
    description: The key to use for the cache
    required: true
  cache-hit:
    description: Whether the cache was hit during setup
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    
    - name: Check cache status
      shell: bash
      run: |
        if [[ "${{ inputs.cache-hit }}" == "true" ]]; then
          echo "::notice ::Cache was hit during setup. Skipping cache save."
        else
          echo "::notice ::Cache was not hit during setup. Proceeding with cache save."
        fi
    
    # We have to clear out git tracked files to avoid them being saved to the cache and causing confusion.
    - name: Git empty and Prune pnpm store
      if: inputs.cache-hit != 'true'
      id: prune
      continue-on-error: true
      shell: bash
      run: git config gc.auto 0 && git gc && ( git fetch origin empty --depth=1 && git checkout origin/empty || git ls-files -z | xargs -0 rm -f ) && pnpm store prune

    - name: Freeze BTRFS
      if: inputs.cache-hit != 'true' && steps.prune.outcome == 'success'
      shell: bash
      working-directory: /mnt
      run: sudo fsfreeze -f "${GITHUB_WORKSPACE}"

    - name: Upload BTRFS Chunks
      if: inputs.cache-hit != 'true' && steps.prune.outcome == 'success'
      uses: actions/cache/save@v4
      with:
        path: /mnt/btrfs_chunks
        key: ${{ inputs.key }}

    - name: Unfreeze BTRFS
      if: inputs.cache-hit != 'true' && steps.prune.outcome == 'success'
      shell: bash
      working-directory: /mnt
      run: sudo fsfreeze -u "${GITHUB_WORKSPACE}"