name: Save BTRFS
description: Composite action that sets up the BTRFS volume for the runner
inputs:
  key:
    description: The key to use for the cache
    required: true
  cache-hit:
    description: Whether the cache was hit during setup
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    
    - name: Check cache status
      shell: bash
      run: |
        if [[ "${{ inputs.cache-hit }}" == "true" ]]; then
          echo "::notice ::Cache was hit during setup. Skipping cache save."
        else
          echo "::notice ::Cache was not hit during setup. Proceeding with cache save."
        fi
    
    # We have to clear out git tracked files to avoid them being saved to the cache and causing confusion.
    - name: Git empty and Prune pnpm store
      if: inputs.cache-hit != 'true'
      id: prune
      continue-on-error: true
      shell: bash
      run: | # Clean up unreachable objects
        git prune --expire="1 week ago" && echo "Pruned unreachable objects"
        git remote prune origin && echo "pruned remote tracking branches"
        git reflog expire --expire="1 week ago" --all && echo "expired reflog entries"
        ( git for-each-ref --format="%(refname)" refs/original/ | xargs -n 1 git update-ref -d 2>/dev/null ) && echo "removed stale references"
        
        git fetch origin empty --depth=1 && echo "fetched empty"
        ( git checkout origin/empty && echo "checked out empty" ) || ( git ls-files -z | xargs -0 rm -f && echo "removed tracked files" )
        pnpm store prune && echo "pruned pnpm store"

    - name: Prefix key
      if: inputs.cache-hit != 'true' && steps.prune.outcome == 'success'
      id: prefix-cache-key
      uses: actions/github-script@v7
      env:
        BASE_KEY: ${{ inputs.key }}
      with:
        script: |
          if(!process.env.GITHUB_REPOSITORY) {
            throw new Error('GITHUB_REPOSITORY is not set');
          }
          const repoPrefix = `${process.env.GITHUB_REPOSITORY}-`;
          const key = `${repoPrefix}${process.env.BASE_KEY}`;
          core.setOutput('key', key);

    - name: Freeze BTRFS
      if: inputs.cache-hit != 'true' && steps.prune.outcome == 'success'
      shell: bash
      working-directory: /mnt
      run: sudo fsfreeze -f "${GITHUB_WORKSPACE}"

    - name: Upload BTRFS Chunks
      if: inputs.cache-hit != 'true' && steps.prune.outcome == 'success'
      uses: actions/cache/save@v4
      with:
        path: /mnt/btrfs_chunks
        key: ${{ steps.prefix-cache-key.outputs.key }}

    - name: Unfreeze BTRFS
      if: inputs.cache-hit != 'true' && steps.prune.outcome == 'success'
      shell: bash
      working-directory: /mnt
      run: sudo fsfreeze -u "${GITHUB_WORKSPACE}"